class ApiErrorCode {
  static SYSTEM_ERROR = "SYSTEM_ERROR";
  static LOGIN_FAILED = "LOGIN_FAILED";
  static AUTH_FAILED = "AUTH_FAILED";
  static ARGURMENT_REQUIRED = "ARGURMENT_REQUIRED";
  static UNAUTHORIZED = "UNAUTHORIZED";
  static USER_EXISTED = "USER_EXISTED";
  static EMAIL_INVALID = "EMAIL_INVALID";
  static SELF_UPDATE_ADMIN_RIGHTS = "SELF_UPDATE_ADMIN_RIGHTS";
  static PASSWORD_CHANGED_REQUIRED = "PASSWORD_CHANGED_REQUIRED";
  static PASSWORD_NO_DIFFERENCE = "PASSWORD_NO_DIFFERENCE";
  static OLD_PASSWORD_INCORRECT = "OLD_PASSWORD_INCORRECT";
  static USER_NOT_EXISTED = "USER_NOT_EXISTED";
  static DELETE_YOURSELF = "DELETE_YOURSELF";
  static USERGROUP_EXISTED = "USERGROUP_EXISTED";
  static USERGROUP_NOT_EXISTED = "USERGROUP_NOT_EXISTED";
  static PARAM_NOT_FOUND = "PARAM_NOT_FOUND";
  static CSV_FILE_REQUIRED = "CSV_FILE_REQUIRED";
  static EXISTED_MAC_ADDRESS = "EXISTED_MAC_ADDRESS";
  static EXISTED_IP_ADDRESS = "EXISTED_IP_ADDRESS";
  static EXISTED_NAME = "EXISTED_NAME";
  static NOT_EXISTED = "NOT_EXISTED";
  static CATEGORY_NOT_EXISTED = "CATEGORY_NOT_EXISTED";
  static CAMERA_NOT_EXISTED = "CAMERA_NOT_EXISTED";
  static NOT_FOUND = "NOT_FOUND";
  static EXCEED_60_MINS = "EXCEED_60_MINS";
  static INVALID_END_TIME = "INVALID_END_TIME";
  static INVALID_POLYGON = "INVALID_POLYGON";
  static INVALID_POLYGON_POINT = "INVALID_POLYGON_POINT";
  static INVALID_POINT_IN_PERCENT = "INVALID_POINT_IN_PERCENT";
  static VIDEO_EXPIRED = "VIDEO_EXPIRED";
  static ROOT_MAP_EXISTED = "ROOT_MAP_EXISTED";
  static PARENT_MAP_NOT_FOUND = "PARENT_MAP_NOT_FOUND";
  static CAMERA_EXISTS_ON_OTHER_MAP = "CAMERA_EXISTS_ON_OTHER_MAP";
  static NOT_SUPPORTED = "NOT_SUPPORTED";
  static FACE_RECOGNITION_API_SERVER_NOT_RUNNING =
    "FACE_RECOGNITION_API_SERVER_NOT_RUNNING";
}
